language: cpp

env: CXX=/usr/bin/clang++ CC=/usr/bin/clang

# Setup repos etc before installation
before_install:
  - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main'
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get update
  - apt-cache search clang
# Install dependencies
install:
  - sudo apt-get install clang-3.5
  - mkdir -p third_party
  - cd third_party
  - wget https://googletest.googlecode.com/files/gtest-1.7.0.zip
  - unzip -o -q gtest-1.7.0.zip
  - cd gtest-1.7.0
  - cmake -DCMAKE_CXX_FLAGS="-std=c++11" .
  - cmake --build

branches:
  only:
    - master

script:
  - make test
